version: "3.7"

services:
  postgresql:
    image: postgres:latest
    container_name: "postgresql"
    restart: "always"
    expose:
      - "5432"
    env_file: "./postgresql/.env"
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"

  backend:
    build: "./backend"
    container_name: "backend"
    restart: "always"
    expose:
      - "8000"
    env_file: "./backend/.env"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
    volumes:
      - "./backend:/backend"
      - "static_volume:/backend/static"
      - "media_volume:/backend/media"
    depends_on:
      - "postgresql"

  nginx:
    build: "./nginx"
    container_name: "nginx"
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "static_volume:/backend/static"
      - "media_volume:/backend/media"
    depends_on:
      - "postgresql"
      - "backend"

volumes:
  static_volume:
    external: true
  media_volume:
    external: true
