# Generated by Django 4.0.3 on 2022-05-29 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
        ('cart', '0001_initial'),
        ('ecommerce_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemhit',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_account.ipaddress'),
        ),
        migrations.AddField(
            model_name='itemhit',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='category.category', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='item',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_items', to=settings.AUTH_USER_MODEL, verbose_name='دیس لایک'),
        ),
        migrations.AddField(
            model_name='item',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='cart.ItemHit', to='ecommerce_account.ipaddress', verbose_name='بازدید ها'),
        ),
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_items', to=settings.AUTH_USER_MODEL, verbose_name='لایک'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart.item', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='carts', to='cart.cartitem', verbose_name='محصولات'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
